/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class QuoteTest {
    Reader reader;
    @Before
    public void init() {
         reader = new Reader("src/main/resources/recentquotes.json");

    }

    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
