/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class ReaderTest {
    private Reader reader;

    @Test
    public void initStarWars() {
        reader = new Reader("src/main/resources/starwars.txt", "");
        assertNotNull("Reader has been initialized and should not be null", reader);
        assertNull("quote array should be empty at just initialized reader", reader.getQuotes());
    }

    @Test public void addOneQuote() {
        reader = new Reader("src/main/resources/starwars.txt",
                "http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");
        reader.fetchFromAPI();
        assertNull("Successful pull from quote means array is not populated, array should be null",
                reader.getQuotes());
    }

    @Test public void wrongApiUrlButFileExists() {
        reader = new Reader("src/main/resources/starwars.txt",
                "wrongUrl");
        reader.fetchFromAPI();
        assertNotNull("Wrong url means array should be populated, 1 expected",
                reader.getQuotes());
    }

    @Test public void wrongUrlPlusNoFile() {
        reader = new Reader("blah",
                "boo");
        reader.fetchFromAPI();
        assertNotNull("wrong url and non-existing file means pull from internal, array should be populated",
                reader.getQuotes());
    }

}
