/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class ReaderTest {
    private Reader reader;

    @Test (expected = IllegalArgumentException.class)
    public void wrongFile() {
        reader = new Reader("src/doesNotExist.json");
    }

    @Before
    public void init() {
         reader = new Reader("src/main/resources/oneQuote.json");

    }

    @Test public void quote() {
        //there is literally only one quote in the file - george orwell
        assertEquals("Should return the one quote contained in file",
                "George Orwell\n" +
                        " “His answer to every problem, every setback was “I will work harder!” —which he had adopted as his personal motto.” ",
                reader.getRandomQuote());
    }

    @Test public void checkSize() {
        assertEquals("length of array should be 1",
                1, reader.getQuotes().length);
    }
}
